### ISSUE TITLE
404 images & videos

### ISSUE THREAD

**Issue by gregsadetsky** [ScrollPrize/scrollprize-website#1]
Hey,

Just found [some references](https://github.com/ScrollPrize/scrollprize-website/blob/main/docs/05_tutorial2.md?plain=1#L159-L161) to an image & 2 videos that point to a folder that doesn't exist:

```
  <video autoPlay playsInline loop muted className="max-w-[100%] rounded-xl" poster="/img/tutorials2/imagej-raw-xrays2.jpg">
    <source src="/img/tutorials2/imagej-raw-xrays2.webm" type="video/webm"/>
    <source src="/img/tutorials2/imagej-raw-xrays2.mp4" type="video/mp4"/>
```

This is what it looks like on the site:

<img width="555" alt="image" src="https://user-images.githubusercontent.com/1017304/225883504-05b2bc3c-3445-43d4-b632-8172107c03cb.png">

The 3 files seem to be under `tutorials` rather than `tutorials2`. I'll check locally and commit a PR.

---

Looking at the devtools. I see a few more 404 image references -- I'll open a separate issue for those

<img width="601" alt="image" src="https://user-images.githubusercontent.com/1017304/225883630-a5596976-c34c-4ce3-a34c-405e897cf647.png">

**Comment by janpaul123** [comment]
Also fixed in ddb913ed3464887e89e98bd604012a25553f191c :)
